version: 2

models:
  - name: model_data_a
    columns:
      - name: col_a
        description: 'description column "a"'
  - name: Case_Sensitive_Model
    columns:
      - name: col_A
        description: 'description column "a"'